include ../../../make.env

all:
	$(MAKE) -C smtp_wrapper

install:
	$(MAKE) -C smtp_wrapper install

clean:
	$(MAKE) -C smtp_wrapper clean

uninstall: dummy
	$(MAKE) -C smtp_wrapper uninstall

package: dummy
	$(MAKE) -C smtp_wrapper package

dummy:
