<?
regGS("CAMPSITE","CAMPSITE");
regGS("Home","Glavna");
regGS("Logout","Izlaz");
regGS("Fields","Polja");
regGS("Delete","Izbri¹i");
regGS("Type","Tip");
regGS("Name","Ime");
regGS("Keyword","Kljuène reèi");
regGS("Infotypes","Infotipi");
regGS("Languages","Jezici");
regGS("Native name","Ime u originalu");
regGS("Code","Kod");
regGS("Code page","Kodna stranica");
regGS("Edit","Izmeni");
regGS("Countries","Zemlje");
regGS("Reader","Èitalac");
regGS("Access","Pristup");
regGS("Login","Ulaz");
regGS("Password","Lozinka");
regGS("Site","Sajt");
regGS("Currency","Valuta");
regGS("Templates","©abloni");
regGS("Topics","Teme");
regGS("Path","Putanja");
regGS("Go up","Gore");
regGS("Language","Jezik");
regGS("Keyword infotype","Infotip za kljuènu reè");
regGS("Translation","Prevod");
regGS("Infotype","Infotip");
regGS("Country","Zemlja");
regGS("User name","Korisnièko ime");
regGS("Definition","Definicija");
regGS("Publication","Publikacija");
regGS("Default language","Osnovni jezik");
regGS("Time Unit","Vremenska jedinica");
regGS("Unit Cost","Cena jedinice");
regGS("Subscriptions","Pretplata");
regGS("Issue","Izdanje");
regGS("Number","Broj");
regGS("Section","Rubrika");
regGS("Keywords","Kljuène reèi");
regGS("Next","Napred");
regGS("Previous","Nazad");
regGS("Translate","Prevedi");
regGS("Details","Detalji");
regGS("View","Prikaz");
regGS("days","Dani");
regGS("Article Types","Tipovi èlanaka");
regGS("Dictionary Infotypes","Infotip u glosaru");
regGS("User Types","Vrsta korisnika");
regGS("Glossary","Glosar");
regGS("Keyword infotypes","Infotipi za kljuène reèi");
regGS("Publications","Publikacije");
regGS("Issues","Izdanja");
regGS("Sections","Rubrike");
regGS("Articles","Èlanci");
regGS("Images","Slike");
regGS("Nr","Br");
regGS("Change","Izmeni");
regGS("Add new issue","Dodaj novo izdanje");
regGS("Default Language","Osnovni jezik");
regGS("Subscription Default Time","Osnovna du¾ina pretplate");
regGS("Pay Period","Rok plaæanja");
regGS("Info","Info");
regGS("Trial Period","Probni period");
regGS("Paid Period","Plaæeni period");
regGS("Preview","Vidi kako izgleda");
regGS("You must complete the $1 field.","Morate da ispunite $1 polje");
regGS("No such language.","Nema takvog jezika");
regGS("No such infotype.","Nema takvog infotipa");
regGS("No such keyword.","Nema takve kljuène reèi");
regGS("No such publication.","Nema takve publikacije");
regGS("No such country.","Nema takve zemlje u databazi");
regGS("No such issue.","Takvo izdanje ne postoji");
regGS("You must select a language.","Morate odabrati jezik");
regGS("No such section.","Takva rubrika ne postoji");
regGS("No articles.","Nema èlanaka");
regGS("Add new article","Dodaj novi èlanak");
regGS("Status","Status");
regGS("No such article.","Nema tog èlanka");
regGS("Published","Objavljen");
regGS("Submitted","Predat");
regGS("New","Nov");
regGS("Article","Èlanak");
regGS("Publish","Objavi");
regGS("Unpublish","Povuci");
regGS("Unlock","Otkljuèaj");
regGS("Uploaded","Aploudovan");
regGS("(yyyy-mm-dd)","gggg-mm-dd");
regGS("YYYY-MM-DD","GGGG-MM-DD");
regGS("Submit","Predaj");
regGS("Field","Polje");
regGS("Edit details","Izmeni detalje");
regGS("No such image.","Nema te slike");
regGS("Image","Slika");
regGS("Description","Opis");
regGS("Photographer","Fotograf");
regGS("Place","Mesto");
regGS("Date","Datum");
regGS("Publ. no.","Br. pub.");
regGS("Issue no.","Br. izdanja");
regGS("Section no.","Br. rubrike");
regGS("Image number","Br. slike");
regGS("Users","Korisnici");
regGS("User is a reader","Korisnik je èitalac");
regGS("User may add/change publications","Korisnik sme da dodaje/menja publikacije");
regGS("User may delete publications","Korisnik sme da bri¹e publikacije");
regGS("User may add/change issues","Korisnik sme da dodaje/ureðuje izdanja");
regGS("User may delete issues","Korisnik sme da bri¹e izdanja");
regGS("User may add/change sections","Korisnik sme da dodaje/ureðuje rubrike");
regGS("User may delete sections","Korisnik sme da bri¹e rubrike");
regGS("User may add articles","Korisnik sme da dodaje èlanke");
regGS("User may change articles","Korisnik sme da ureðuje èlanke");
regGS("User may delete articles","Korisnik sme da bri¹e èlanke");
regGS("User may add images","Korisnik sme da dodaje slike");
regGS("User may change images","Korisnik sme da menja slike");
regGS("User may delete images","Koriisnik sme da bri¹e slike");
regGS("User may add templates","Korisinik sme da dodaje ¹ablone");
regGS("User may delete templates","Korisnik sme da bri¹e ¹ablone");
regGS("User may add/change user accounts and passwords","Korisnik sme da dodaje/menja korisnièke profile i lozinke");
regGS("User may delete user accounts","Korisnik sme da bri¹e korisnièke profile");
regGS("User may manage user subscriptions","Korisnik sme da administrira pretplatu");
regGS("User may manage account types","Korisnik sme da ureðuje vrste korisnièkih profila");
regGS("User may add/change article types","Korisnik sme da dodaje/menja tipove èlanaka");
regGS("User may delete article types","Korisnik sme da bri¹e tipove èlanaka");
regGS("User may add languages and manage language information","Korisnik sme da dodaje jezike i menja relevantne informacije");
regGS("User may delete languages","Korisnik sme da bri¹e jezike");
regGS("User may manage dictionary classes","Korisnik sme da manipuli¹e sa infotipovima");
regGS("User may manage glossary infotypes","Korisnik sme da manipuli¹e infotipovima u glosaru");
regGS("User may add/change dictionary entries","Korisnik sme da dodaje/menja jedinice u glosaru");
regGS("User may add/change glossary entries","");
regGS("User may delete dictionary entries","Korisnik sme da bri¹e jedinice u glosaru");
regGS("User may delete glossary entries","");
regGS("User will be notified on several events","Korisnik æe biti obave¹tavan o raznim sistemskim aktivnostima");
regGS("User may view audit logs","Korisnik ima pristup logovima");
regGS("User may add/change country names","Korisnik sme da dodaje/menja imena zemalja");
regGS("User may delete country entries","Korisnik sme da bri¹e zemlje");
regGS("User may manage localizer","Korisnik sme da koristi lokalizator");
regGS("User may manage indexer","Korisnik sme da upravlja indeksatorom");
regGS("User may publish articles","Korisnik sme da objavljuje èlanke");
regGS("User may manage topics","Korisnik sme da upravlja temama");
regGS("Adding new translation","Dodajem novi prevod");
regGS("Translate keyword","Prevedi kljuènu reè");
regGS("No more languages.","Nema vi¹e nijednog jezika");
regGS("No such keyword infotype.","Nema takvog infotipa za kljuènu reè");
regGS("Adding new keyword infotype","Dodajem novi infotip za kljuènu reè");
regGS("The infotype has been deleted.","Infotip je izbrisan");
regGS("The infotype could not be deleted.","Infotip nije mogao da bude izbrisan");
regGS("Add new publication","Dodaj novu publikaciju");
regGS("Upload new template","Aplouduj novi ¹ablon");
regGS("Add new user account","Dodaj novog korisnika");
regGS("Add new user type","Dodaj novi tip korisnika");
regGS("Add new article type","Dodaj novi tip èlanka");
regGS("Add new country","Dodaj novu zemlju");
regGS("Add new language","Dodaj novi jezik");
regGS("Add new section","Dodaj novu rubriku");
regGS("View logs","Pogledaj log");
regGS("Change your password","Promeni lozinku");
regGS("Your articles","Va¹i èlanci");
regGS("Submitted articles","Predati èlanci");
regGS("Quick Menu","Preèice");
regGS("Logs","Logovi");
regGS("There are $1 article(s) left.","Preostao-lo je jo¹ $1 èlanak-a");
regGS("There are $1 issue(s) left.","Preostalo-la je(su) jo¹ $1 izdanje-a");
regGS("There are $1 section(s) left.","Preostala(o) je jo¹ $1 rubrika(e)");
regGS("There are $1 publication(s) left.","Preostala(o) je jo¹ $1 publikacija(e) ");
regGS("There are $1 keyword(s) left.","Preostala(e) je (su) jo¹ $1 kljuèna(e) reèi");
regGS("There are $1 countries left.","Preostala(le) je (su) jo¹ $1 zemlja(e)");
regGS("Name<BR><SMALL>(click to edit)</SMALL>","Ime<br><small>(kliknite da uðete)</small>");
regGS("User account","Korisnièki profil");
regGS("No such user account.","Nema takvog korisnièkog profila.");
regGS("Add new subscription","Dodaj novu pretplatu");
regGS("You do not have the right to add subscriptions.","Nemate pravo da dodajete nove pretplate");
regGS("Adding subscription","Dodajem pretplatu");
regGS("The section could not be added.","Rubrika nije mogla da bude dodata");
regGS("Delete subscription","Izbri¹i pretplatu");
regGS("You do not have the right to delete subscriptions.","Nemate pravo da bri¹ete pretplate");
regGS("Deleting subscription","Bri¹em pretplatu");
regGS("No such subscription.","Nema takve pretplate.");
regGS("The section $1 could not be deleted.","Rubrika $1 nije mogla da se izbri¹e.");
regGS("Yes","Da");
regGS("No","Ne");
regGS("No issues.","Nema nikakvih izdanja.");

?>