<?
regGS("CAMPSITE","CAMPSITE");
regGS("Home","Pagina principalã");
regGS("Logout","Închide sesiunea");
regGS("Fields","Cîmpuri");
regGS("Delete","ªterge");
regGS("Type","Tip");
regGS("Name","Nume");
regGS("Keyword","Cuvînt cheie");
regGS("Infotypes","Tipuri de informaþie");
regGS("Languages","Limbi");
regGS("Native name","Nume in limba originalã");
regGS("Code","Cod");
regGS("Code page","Cod de paginã");
regGS("Edit","Editeazã");
regGS("Countries","Þãri");
regGS("Reader","Cititor");
regGS("Access","Acces");
regGS("Login","Deschide sesiune");
regGS("Password","Parola");
regGS("Site","Sit");
regGS("Currency","Monedã");
regGS("Templates","");
regGS("Topics","Topic");
regGS("Path","Cale");
regGS("Go up","Un nivel mai sus");
regGS("Language","Limbã");
regGS("Keyword infotype","Tipul de informaþie al cuvîntului cheie");
regGS("Translation","Traducere");
regGS("Infotype","Tip de informaþie");
regGS("Country","Þarã");
regGS("User name","Nume utilizator");
regGS("Definition","Definiþie");
regGS("Publication","Publicaþie");
regGS("Default language","Limba implicitã");
regGS("Time Unit","Unitatea de timp");
regGS("Unit Cost","Costul unitãþii de timp");
regGS("Subscriptions","Subscrieri");
regGS("Issue","Ediþie");
regGS("Number","Numãr");
regGS("Section","Secþiune");
regGS("Keywords","Cuvinte cheie");
regGS("Next","Urmãtorul");
regGS("Previous","Anteriorul");
regGS("Translate","Tradu");
regGS("Details","Detalii");
regGS("View","Vedere");
regGS("days","zile");
regGS("Article Types","Tipuri de articole");
regGS("Dictionary Infotypes","Tipui de informaþii din dicþionar");
regGS("User Types","Tipuri de utilizatori");
regGS("Glossary","Glosar");
regGS("Keyword infotypes","Tipuri de informaþie ale cuvîntului cheie");
regGS("Publications","Publicaþii");
regGS("Issues","Ediþii");
regGS("Sections","Secþiuni");
regGS("Articles","Articole");
regGS("Images","Imagini");
regGS("Nr","Nr");
regGS("Change","Modificã");
regGS("Add new issue","Adaugã editie nouã");
regGS("Default Language","Limba implicitã");
regGS("Subscription Default Time","Timpul implicit de subscriere");
regGS("Pay Period","Periodata de platã");
regGS("Info","Informaþii");
regGS("Trial Period","Perioada de probã");
regGS("Paid Period","Perioada cu platã");
regGS("Preview","Vizualizare");
regGS("You must complete the $1 field.","Trebuie sã completaþi cîmpul $1");
regGS("No such language.","Limba nu existã");
regGS("No such infotype.","Tipul de informaþie nu existã");
regGS("No such keyword.","Cuvîntul cheie nu existã");
regGS("No such publication.","Publicaþia nu existã");
regGS("No such country.","Þara nu existã");
regGS("No such issue.","Ediþia nu existã");
regGS("You must select a language.","Trebuie sã selectaþi o limbã");
regGS("No such section.","Secþiunea nu existã");
regGS("No articles.","Nu existã articole");
regGS("Add new article","Adaugã articol nou");
regGS("Status","Stare");
regGS("No such article.","Articolul nu existã");
regGS("Published","Publicat");
regGS("Submitted","Anunþat");
regGS("New","Nou");
regGS("Article","Articol");
regGS("Publish","Publicã");
regGS("Unpublish","");
regGS("Unlock","Deblocheazã");
regGS("Uploaded","Salvat");
regGS("(yyyy-mm-dd)","(aaaa-ll-zz)");
regGS("YYYY-MM-DD","AAAA-LL-ZZ");
regGS("Submit","Anunþã");
regGS("Field","Cîmp");
regGS("Edit details","Editeazã detaliile");
regGS("No such image.","Imaginea nu existã");
regGS("Image","Imagine");
regGS("Description","Descriere");
regGS("Photographer","Fotograf");
regGS("Place","Loc");
regGS("Date","Data");
regGS("Publ. no.","Nr. publ.");
regGS("Issue no.","Nr. ediþie");
regGS("Section no.","Nr. secþiune");
regGS("Image number","Numãr imagine");
regGS("Users","Utilizatori");
regGS("User is a reader","Utilizatorul este abonat");
regGS("User may add/change publications","Utilizatorul poate adãuga/modifica publicaþii");
regGS("User may delete publications","Utilizatorul poate ºterge publicaþii");
regGS("User may add/change issues","Utilizatorul poate adãuga/modifica ediþii");
regGS("User may delete issues","Utilizatorul poate ºterge ediþii");
regGS("User may add/change sections","Utilizatorul poate adãuga/modifica secþiuni");
regGS("User may delete sections","Utilizatorul poate ºterge secþiuni");
regGS("User may add articles","Utilizatorul poate adãuga articole");
regGS("User may change articles","Utilizatorul poate modifica articole");
regGS("User may delete articles","Utilizatorul poate ºterge articole");
regGS("User may add images","Utilizatorul poate adãuga imagini");
regGS("User may change images","Utilizatorul poate modifica imagini");
regGS("User may delete images","Utilizatorul poate ºterge imagini");
regGS("User may add templates","Utilizatorul poate adãuga ....");
regGS("User may delete templates","Utilizatorul poate ºterge ...");
regGS("User may add/change user accounts and passwords","Utilizatorul poate adãuga/modifica conturi de utilizator");
regGS("User may delete user accounts","Utilizatorul poate ºterge conturi de utilizator");
regGS("User may manage user subscriptions","Utilizatorul poate modifica subscrieri");
regGS("User may manage account types","Utilizatorul poate modifica tipurile de utilizatori");
regGS("User may add/change article types","Utilizatorul poate adãuga/modifica tipurile de articole");
regGS("User may delete article types","Utilizatorul poate ºterge tipuri de articole");
regGS("User may add languages and manage language information","Utilizatorul poate adãuga limbi si modifica informaþiile despre limbi");
regGS("User may delete languages","Utilizatorul poate limbi");
regGS("User may manage dictionary classes","");
regGS("User may manage glossary infotypes","Utilizatorul poate modifica tipurile de informaþie din glosar");
regGS("User may add/change dictionary entries","Utilizatorul poate adãuga/modifica intrãrile din dicþionar");
regGS("User may add/change glossary entries","");
regGS("User may delete dictionary entries","Utilizatorul poate ºterge intrãri din dicþionar");
regGS("User may delete glossary entries","");
regGS("User will be notified on several events","Utilizatorul va fi anunþat in cazul apariþiei unor evenimente");
regGS("User may view audit logs","Utilizatorul poate vizuliza înregistrãrile din log");
regGS("User may add/change country names","Utilizatorul poate adãuga/modifica þãri");
regGS("User may delete country entries","Utilizatorul poate ºterge þãri");
regGS("User may manage localizer","Utilizatorul poate controla localizatorul");
regGS("User may manage indexer","Utilizatorul poate controla serviciul de indexare");
regGS("User may publish articles","Utilizatorul poate publica articole");
regGS("User may manage topics","Utilizatorul poate modifica topicele");
regGS("Adding new translation","Utilizatorul poate adãuga traduceri");
regGS("Translate keyword","Tradu cuvîntul cheie");
regGS("No more languages.","Nu existã alte limbi");
regGS("No such keyword infotype.","Tipul de informaþie al cuvîntului cheie nu existã");
regGS("Adding new keyword infotype","Adaug noul tip de informaþie al cuvîntului cheie");
regGS("The infotype has been deleted.","Tipul de informaþie a fost ºters");
regGS("The infotype could not be deleted.","Tipul de informaþie nu poate fi ºters");
regGS("Add new publication","Adaugã publicaþie");
regGS("Upload new template","");
regGS("Add new user account","Adaugã utilizator");
regGS("Add new user type","Adaugã tip de utilizator");
regGS("Add new article type","Adaugã tip de articol");
regGS("Add new country","Adaugã þarã");
regGS("Add new language","Adaugã limbã");
regGS("Add new section","Adaugã secþiune");
regGS("View logs","Vizualizare log");
regGS("Change your password","Modificã parola");
regGS("Your articles","Articole personale");
regGS("Submitted articles","Articole anunþate");
regGS("Quick Menu","Meniu rapid");
regGS("Logs","Loguri");
regGS("There are $1 article(s) left.","Mai sînt $1 articole");
regGS("There are $1 issue(s) left.","Mai sînt $1 ediþii");
regGS("There are $1 section(s) left.","Mai sînt $1 secþiuni");
regGS("There are $1 publication(s) left.","Mai sînt $1 publicaþii");
regGS("There are $1 keyword(s) left.","Mai sînt $1 cuvinte cheie");
regGS("There are $1 countries left.","Mai sînt $1 þãri");
regGS("Name<BR><SMALL>(click to edit)</SMALL>","Nume");
regGS("User account","Cont de utilizator");
regGS("No such user account.","Contul de utilizator nu existã");
regGS("Add new subscription","Adaugã subscriere");
regGS("You do not have the right to add subscriptions.","Nu aveþi dreptul de a adãuga subscrieri");
regGS("Adding subscription","Adaug subscriere");
regGS("The section could not be added.","Secþiunea nu poate fi adãugatã");
regGS("Delete subscription","ªterge subscriere");
regGS("You do not have the right to delete subscriptions.","Nu aveþi dreptul de a ºterge subscrieri");
regGS("Deleting subscription","ªterg subscriere");
regGS("No such subscription.","Subscrierea nu existã");
regGS("The section $1 could not be deleted.","Secþiunea $1 nu poate fi ºtearsã");
regGS("Yes","Da");
regGS("No","Nu");
regGS("No issues.","Nu exista ediþii");

?>