<?
regGS("CAMPSITE","");
regGS("Home","Домой:ru");
regGS("Logout","Выход:ru");
regGS("Fields","Поля:ru");
regGS("Delete","Удалить:ru");
regGS("Type","Тип:ru");
regGS("Name","Имя:ru");
regGS("Keyword","Ключевое слово:ru");
regGS("Infotypes","");
regGS("Languages","Язык:ru");
regGS("Native name","Исходное имя:ru");
regGS("Code","Код:ru");
regGS("Code page","Кодовая страница:ru");
regGS("Edit","Правка:ru");
regGS("Countries","Страны:ru");
regGS("Reader","Читатель:ru");
regGS("Access","Доступ:ru");
regGS("Login","Логин:ru");
regGS("Password","Пароль:ru");
regGS("Site","Сайт:ru");
regGS("Currency","Валюта:ru");
regGS("Templates","Шаблоны:ru");
regGS("Topics","");
regGS("Path","");
regGS("Go up","Наверх:ru");
regGS("Language","Язык:ru");
regGS("Keyword infotype","");
regGS("Translation","Перевод:ru");
regGS("Infotype","");
regGS("Country","");
regGS("User name","");
regGS("Definition","");
regGS("Publication","");
regGS("Default language","");
regGS("Time Unit","Единица времени:ru");
regGS("Unit Cost","Стоимость единицы:ru");
regGS("Subscriptions","Подписка:ru");
regGS("Issue","");
regGS("Number","");
regGS("Section","");
regGS("Keywords","");
regGS("Next","Следующ.:ru");
regGS("Previous","Предыдущ.:ru");
regGS("Translate","Перевести:ru");
regGS("Details","Подробности:ru");
regGS("View","Вид:ru");
regGS("days","дней:ru");
regGS("Article Types","Тип статьи:ru");
regGS("Dictionary Infotypes","");
regGS("User Types","Пользовательские типы:ru");
regGS("Glossary","");
regGS("Keyword infotypes","");
regGS("Publications","Публикации:ru");
regGS("Issues","Выпуски:ru");
regGS("Sections","Секции:ru");
regGS("Articles","Статьи:ru");
regGS("Images","Картинки:ru");
regGS("Nr","№:ru");
regGS("Change","Изменить:ru");
regGS("Add new issue","Добавить новый выпуск:ru");
regGS("Default Language","Язык по умолчанию:ru");
regGS("Subscription Default Time","Время подписки по умолчанию:ru");
regGS("Pay Period","");
regGS("Info","Информация:ru");
regGS("Trial Period","");
regGS("Paid Period","");
regGS("Preview","Предварительный просмотр:ru");
regGS("You must complete the $1 field.","Вы должны заполнить $1 поле.:ru");
regGS("No such language.","Нет такого языка.:ru");
regGS("No such infotype.","");
regGS("No such keyword.","Нет такого ключевого слова.:ru");
regGS("No such publication.","Нет такой публикации.:ru");
regGS("No such country.","Нет такой страны.:ru");
regGS("No such issue.","Неттакого выпуска.:ru");
regGS("You must select a language.","Вы должны выбрать язык.:ru");
regGS("No such section.","");
regGS("No articles.","");
regGS("Add new article","");
regGS("Status","");
regGS("No such article.","");
regGS("Published","");
regGS("Submitted","");
regGS("New","");
regGS("Article","");
regGS("Publish","");
regGS("Unpublish","");
regGS("Unlock","");
regGS("Uploaded","");
regGS("(yyyy-mm-dd)","");
regGS("YYYY-MM-DD","");
regGS("Submit","");
regGS("Field","");
regGS("Edit details","");
regGS("No such image.","");
regGS("Image","");
regGS("Description","");
regGS("Photographer","");
regGS("Place","");
regGS("Date","");
regGS("Publ. no.","");
regGS("Issue no.","");
regGS("Section no.","");
regGS("Image number","");
regGS("Users","");
regGS("User is a reader","");
regGS("User may add/change publications","");
regGS("User may delete publications","");
regGS("User may add/change issues","");
regGS("User may delete issues","");
regGS("User may add/change sections","");
regGS("User may delete sections","");
regGS("User may add articles","");
regGS("User may change articles","");
regGS("User may delete articles","");
regGS("User may add images","");
regGS("User may change images","");
regGS("User may delete images","");
regGS("User may add templates","");
regGS("User may delete templates","");
regGS("User may add/change user accounts and passwords","");
regGS("User may delete user accounts","");
regGS("User may manage user subscriptions","");
regGS("User may manage account types","");
regGS("User may add/change article types","");
regGS("User may delete article types","");
regGS("User may add languages and manage language information","");
regGS("User may delete languages","");
regGS("User may manage glossary infotypes","");
regGS("User may add/change dictionary entries","");
regGS("User may delete dictionary entries","");
regGS("User will be notified on several events","");
regGS("User may view audit logs","");
regGS("User may add/change country names","");
regGS("User may delete country entries","");
regGS("User may manage localizer","");
regGS("User may manage indexer","");
regGS("User may publish articles","");
regGS("User may manage topics","");
regGS("","");
regGS("Adding new translation","");
regGS("Translate keyword","");
regGS("No more languages.","");
regGS("No such keyword infotype.","");
regGS("Adding new keyword infotype","");
regGS("The infotype has been deleted.","");
regGS("The infotype could not be deleted.","");
regGS("Add new publication","");
regGS("Upload new template","");
regGS("Add new user account","");
regGS("Add new user type","");
regGS("Add new article type","");
regGS("Add new country","");
regGS("Add new language","");
regGS("Add new section","");
regGS("View logs","");
regGS("Change your password","");
regGS("Your articles","");
regGS("Submitted articles","");
regGS("Quick Menu","");
regGS("Logs","");
regGS("There are $1 articles(s) left.","");
regGS("There are $1 issues(s) left.","");
regGS("There are $1 section(s) left.","");
regGS("There are $1 publication(s) left.","");
regGS("There are $1 keywords(s) left.","");
regGS("There are $1 infotypes(s) left.","");
regGS("There are $1 countries left.","");
regGS("Subscription default time","");
regGS("Name<BR><SMALL>(click to edit)</SMALL>","");
regGS("User account","");
regGS("No such user account.","");
regGS("Add new subscription","");
regGS("You do not have the right to add subscriptions.","");
regGS("Adding subscription","");
regGS("The section could not be added.","");
regGS("Delete subscription","");
regGS("You do not have the right to delete subscriptions.","");
regGS("Deleting subscription","");
regGS("No such subscription.","");
regGS("The section $1 could not be deleted.","");
regGS("Yes","Da");
regGS("No","NO");
regGS("No issues.","");

?>