<?

regGS("CAMPSITE","CAMPSITE");
regGS("Home","Domù");
regGS("Logout","Odhlásit");
regGS("Fields","Pole");
regGS("Delete","Smazat");
regGS("Type","Typ");
regGS("Name","Název");
regGS("Keyword","Klíèové slovo");
regGS("Infotypes","Infotypy");
regGS("Languages","Jazyk");
regGS("Native name","Jazyk (nepøelo¾en)");
regGS("Code","Kód");
regGS("Code page","Stránkové kódování");
regGS("Edit","Upravit");
regGS("Countries","Zemì");
regGS("Reader","Ètenáø");
regGS("Access","Pøístup");
regGS("Login","Pøihlásit se");
regGS("Password","Heslo");
regGS("Site","Site");
regGS("Currency","Mìna");
regGS("Templates","©ablony");
regGS("Topics","Témata");
regGS("Path","Cesta");
regGS("Go up","Nahoru");
regGS("Language","Jazyk");
regGS("Keyword infotype","Klíèové slovo (Infotyp)");
regGS("Translation","Pøeklad");
regGS("Infotype","Infotyp");
regGS("Country","Zemì");
regGS("User name","U¾ivatelské jméno");
regGS("Definition","Definice");
regGS("Publication","Publikace");
regGS("Default language","Výchozí jazyk");
regGS("Time Unit","Èasová jednotka");
regGS("Unit Cost","Mìnová jednotka");
regGS("Subscriptions","Pøedplatné");
regGS("Issue","Vydání");
regGS("Number","Èíslo");
regGS("Section","Oddíl");
regGS("Keywords","Klíèová slova");
regGS("Next","Dal¹í");
regGS("Previous","Pøedchozí");
regGS("Translate","Pøeklad");
regGS("Details","Detaily");
regGS("View","Náhled");
regGS("days","dny");
regGS("Article Types","Typ èlánku");
regGS("Dictionary Infotypes","Slovníkové infotypy");
regGS("User Types","U¾ivatelské typy");
regGS("Glossary","Glosáø");
regGS("Keyword infotypes","Klíèová slova (Infotypy)");
regGS("Publications","Publikace");
regGS("Issues","Vydání");
regGS("Sections","Rubriky");
regGS("Articles","Èlánky");
regGS("Images","Obrázky");
regGS("Nr","è.");
regGS("Change","Zmìnit");
regGS("Add new issue","Pøidat nové vydání");
regGS("Default Language","Výchozí jazyk");
regGS("Subscription Default Time","Pøedplatné období");
regGS("Pay Period","Platební období");
regGS("Info","Irformace");
regGS("Trial Period","Zku¹ební období");
regGS("Paid Period","Zaplacené období");
regGS("Preview","Náhled");
regGS("You must complete the $1 field.","Vyplòte $1 pole");
regGS("No such language.","Jazyk neexistuje");
regGS("No such infotype.","Infotyp neexistuje");
regGS("No such keyword.","Klíèové slovo neexistuje");
regGS("No such publication.","Publikace neexistuje");
regGS("No such country.","Zemì neexistuje");
regGS("No such issue.","Vydání neexistuje");
regGS("You must select a language.","Vyberte jazyk");
regGS("No such section.","Rubrika neexistuje");
regGS("No articles.","Èlánky neexistují");
regGS("Add new article","Pøidat nový èlánek");
regGS("Status","Status");
regGS("No such article.","Èlánek neexistuje");
regGS("Published","Zveøejnìno");
regGS("Submitted","Podáno");
regGS("New","Nový");
regGS("Article","Èlánek");
regGS("Publish","Zveøejnit");
regGS("Unpublish","Nezveøejòovat");
regGS("Unlock","Odemknout");
regGS("Uploaded","Nahráno");
regGS("(yyyy-mm-dd)","rrrr-mm-dd");
regGS("YYYY-MM-DD","RRRR-MM-DD");
regGS("Submit","Podat");
regGS("Field","Pole");
regGS("Edit details","Editovat detaily");
regGS("No such image.","Obrázek neexistuje");
regGS("Image","Obrázek");
regGS("Description","Popis");
regGS("Photographer","Fotograf");
regGS("Place","Místo");
regGS("Date","Datum");
regGS("Publ. no.","Publikace è.");
regGS("Issue no.","Vydání è.");
regGS("Section no.","Rubrika è.");
regGS("Image number","Obrázek è.");
regGS("Users","U¾ivatelé");
regGS("User is a reader","U¾ivatel mù¾e pouze èíst");
regGS("User may add/change publications","U¾ivatel mù¾e pøidat/zmìnit publikace");
regGS("User may delete publications","U¾ivatel mù¾e smazat publikace");
regGS("User may add/change issues","U¾ivatel mù¾e pøidat/zmìnit vydání");
regGS("User may delete issues","U¾ivatel mù¾e smazat vydání");
regGS("User may add/change sections","U¾ivatel mù¾e pøidat/zmìnit rubriky");
regGS("User may delete sections","U¾ivatel mù¾e smazat rubriky");
regGS("User may add articles","U¾ivatel mù¾e pøidat èlánky");
regGS("User may change articles","U¾ivatel mù¾e zmìnit èlánky");
regGS("User may delete articles","U¾ivatel mù¾e smazat èlánky");
regGS("User may add images","U¾ivatel mù¾e pøidat obrázky");
regGS("User may change images","U¾ivatel mù¾e zmìnit obrázky");
regGS("User may delete images","U¾ivatel mù¾e smazat obrázky");
regGS("User may add templates","U¾ivatel mù¾e pøidat ¹ablony");
regGS("User may delete templates","U¾ivatel mù¾e smazat ¹ablony");
regGS("User may add/change user accounts and passwords","U¾ivatel mù¾e pøidat/zmìnit u¾ivatelské úèty a hesla");
regGS("User may delete user accounts","U¾ivatel mù¾e mazat u¾ivatelské úèty");
regGS("User may manage user subscriptions","U¾ivatel mù¾e spravovat pøedplatné");
regGS("User may manage account types","U¾ivatel mù¾e zmìnit typy úètu");
regGS("User may add/change article types","U¾ivatel mù¾e pøidat/zmìnit typy èlánku");
regGS("User may delete article types","U¾ivatel mù¾e smazat typy èlánkù");
regGS("User may add languages and manage language information","U¾ivatel mù¾e pøidat a spravovat jazyky");
regGS("User may delete languages","U¾ivatel mù¾e mazat jazyky");
regGS("User may manage glossary infotypes","U¾ivatel mù¾e spravovat infotypy glosáøe");
regGS("User may add/change dictionary entries","U¾ivatel mù¾e pøidat/zmìnit polo¾ky ve slovníku");
regGS("User may delete dictionary entries","U¾ivatel mù¾e smazat polo¾ky ve slovníku");
regGS("User will be notified on several events","U¾ivatel bude nìkolikrát informován");
regGS("User may view audit logs","U¾ivatel mù¾e nahlí¾et do logu");
regGS("User may add/change country names","U¾ivatel mù¾e pøidat/mìnit názvy zemí");
regGS("User may delete country entries","U¾ivatel mù¾e mazat názvy zemí");
regGS("User may manage localizer","U¾ivatel mù¾e spravovat lokalizátor");
regGS("User may manage indexer","U¾ivatel mù¾e spravovat indexátor");
regGS("User may publish articles","U¾ivatel mù¾e zveøejòovat èlánky");
regGS("User may manage topics","U¾ivatel mù¾e spravovat témata");
regGS("Adding new translation","Pøidávání nového pøekladu");
regGS("Translate keyword","Pøelo¾it klíèové slovo");
regGS("No more languages.","®ádné dal¹í jazyky");
regGS("No such keyword infotype.","Infotyp klíèového slova neexistuje");
regGS("Adding new keyword infotype","Pøidávání infotypu klíèového slova");
regGS("The infotype has been deleted.","Infotyp byl smazán");
regGS("The infotype could not be deleted.","Infotyp nemohl být smazán");
regGS("Add new publication","Pøidat novou publikaci");
regGS("Upload new template","Nahrát novou ¹ablonu");
regGS("Add new user account","Pøidat u¾ivatelský úèet");
regGS("Add new user type","Pøidat typ u¾ivatele");
regGS("Add new article type","Pøidat nový typ èlánku");
regGS("Add new country","Pøidat novou zemi");
regGS("Add new language","Pøidat nový jazyk");
regGS("Add new section","Pøidat novou rubriku");
regGS("View logs","Náhled logu");
regGS("Change your password","Zmìnit heslo");
regGS("Your articles","Tvé èlánky");
regGS("Submitted articles","Podané èlánky");
regGS("Quick Menu","Zkratky");
regGS("Logs","Logy");
regGS("There are $1 articles(s) left.","Zbývají èlánky $1");
regGS("There are $1 issues(s) left.","Zbývá èlánek $1");
regGS("There are $1 section(s) left.","Zbývá rubrika $1");
regGS("There are $1 publication(s) left.","Zbývá publikace $1");
regGS("There are $1 keywords(s) left.","Zbývají klíèová slova $1");
regGS("There are $1 infotypes(s) left.","Zbývají infotypy $1");
regGS("There are $1 countries left.","Zbývají zemì $1");
regGS("Name<BR><SMALL>(click to edit)</SMALL>","Název (kliknìte pro editaci)");
regGS("User account","U¾ivatelský úèet");
regGS("No such user account.","U¾ivatelský úèet neexistuje");
regGS("Add new subscription","Pøidat nové pøedplatné");
regGS("You do not have the right to add subscriptions.","Nemáte právo pøidat pøedplatné");
regGS("Adding subscription","Pøidání pøedplatného");
regGS("The section could not be added.","Rubrika nemohla být pøidána");
regGS("Delete subscription","Smazat pøedplatné");
regGS("You do not have the right to delete subscriptions.","Nemáte právo smazat pøedplatné");
regGS("Deleting subscription","Mazání pøedplatného");
regGS("No such subscription.","Pøedplatné neexistuje");
regGS("The section $1 could not be deleted.","Rubrika $1 nemohla být smazána");
regGS("Yes","Ano");
regGS("No","Ne");
regGS("No issues.","Vydání neexistuje");


?>