<?

regGS("CAMPSITE","CAMPSITE");
regGS("Home","Pagina principala");
regGS("Logout","Inchide sesiunea");
regGS("Fields","Cimpuri");
regGS("Delete","Sterge");
regGS("Type","Tip");
regGS("Name","Nume");
regGS("Keyword","Cuvint cheie");
regGS("Infotypes","Tipuri de informatie");
regGS("Languages","Limbi");
regGS("Native name","Nume in limba originala");
regGS("Code","Cod");
regGS("Code page","Cod de pagina");
regGS("Edit","Editeaza");
regGS("Countries","Tari");
regGS("Reader","Cititor");
regGS("Access","Acces");
regGS("Login","Deschide sesiune");
regGS("Password","Parola");
regGS("Site","Sit");
regGS("Currency","Moneda");
regGS("Templates","");
regGS("Topics","Topic");
regGS("Path","Cale");
regGS("Go up","Un nivel mai sus");
regGS("Language","Limba");
regGS("Keyword infotype","Tipul de informatie al cuvintului cheie");
regGS("Translation","Traducere");
regGS("Infotype","Tip de informatie");
regGS("Country","Tara");
regGS("User name","Nume utilizator");
regGS("Definition","Definitie");
regGS("Publication","Publicatie");
regGS("Default language","Limba implicita");
regGS("Time Unit","Unitatea de timp");
regGS("Unit Cost","Costul unitatii de timp");
regGS("Subscriptions","Subscrieri");
regGS("Issue","Editie");
regGS("Number","Numar");
regGS("Section","Sectiune");
regGS("Keywords","Cuvinte cheie");
regGS("Next","Urmatorul");
regGS("Previous","Anteriorul");
regGS("Translate","Tradu");
regGS("Details","Detalii");
regGS("View","");
regGS("days","zile");
regGS("Article Types","Tipuri de articole");
regGS("Dictionary Infotypes","");
regGS("User Types","Tipuri de utilizatori");
regGS("Glossary","");
regGS("Keyword infotypes","Tipuri de informatie ale cuvintului cheie");
regGS("Publications","Publicatii");
regGS("Issues","Editii");
regGS("Sections","Sectiuni");
regGS("Articles","Articole");
regGS("Images","Imagini");
regGS("Nr","Nr");
regGS("Change","Modifica");
regGS("Add new issue","Adauga editie noua");
regGS("Default Language","Limba implicita");
regGS("Subscription Default Time","");
regGS("Pay Period","Periodata de plata");
regGS("Info","");
regGS("Trial Period","");
regGS("Paid Period","");
regGS("Preview","");
regGS("You must complete the $1 field.","");
regGS("No such language.","");
regGS("No such infotype.","");
regGS("No such keyword.","");
regGS("No such publication.","");
regGS("No such country.","");
regGS("No such issue.","");
regGS("You must select a language.","");
regGS("No such section.","");
regGS("No articles.","Nu exista articole");
regGS("Add new article","Adauga articol nou");
regGS("Status","Stare");
regGS("No such article.","Nu exista acest articol");
regGS("Published","Publicat");
regGS("Submitted","");
regGS("New","Nou");
regGS("Article","Articol");
regGS("Publish","Publica");
regGS("Unpublish","");
regGS("Unlock","Deblocheaza");
regGS("Uploaded","");
regGS("(yyyy-mm-dd)","");
regGS("YYYY-MM-DD","");
regGS("Submit","");
regGS("Field","Cimp");
regGS("Edit details","Editeaza detaliile");
regGS("No such image.","Nu exista imaginea");
regGS("Image","Imagine");
regGS("Description","Descriere");
regGS("Photographer","Fotograf");
regGS("Place","Loc");
regGS("Date","Data");
regGS("Publ. no.","Nr. publ.");
regGS("Issue no.","Nr. editie");
regGS("Section no.","Nr. sectiune");
regGS("Image number","Numar imagine");
regGS("Users","Utilizatori");
regGS("User is a reader","Utilizatorul este abonat");
regGS("User may add/change publications","");
regGS("User may delete publications","");
regGS("User may add/change issues","");
regGS("User may delete issues","");
regGS("User may add/change sections","");
regGS("User may delete sections","");
regGS("User may add articles","");
regGS("User may change articles","");
regGS("User may delete articles","");
regGS("User may add images","");
regGS("User may change images","");
regGS("User may delete images","");
regGS("User may add templates","");
regGS("User may delete templates","");
regGS("User may add/change user accounts and passwords","");
regGS("User may delete user accounts","");
regGS("User may manage user subscriptions","");
regGS("User may manage account types","");
regGS("User may add/change article types","");
regGS("User may delete article types","");
regGS("User may add languages and manage language information","");
regGS("User may delete languages","");
regGS("User may manage glossary infotypes","");
regGS("User may add/change dictionary entries","");
regGS("User may delete dictionary entries","");
regGS("User will be notified on several events","");
regGS("User may view audit logs","");
regGS("User may add/change country names","");
regGS("User may delete country entries","");
regGS("User may manage localizer","");
regGS("User may manage indexer","");
regGS("User may publish articles","");
regGS("User may manage topics","");
regGS("Adding new translation","");
regGS("Translate keyword","");
regGS("No more languages.","");
regGS("No such keyword infotype.","");
regGS("Adding new keyword infotype","");
regGS("The infotype has been deleted.","");
regGS("The infotype could not be deleted.","");
regGS("Add new publication","");
regGS("Upload new template","");
regGS("Add new user account","Adauga utilizator");
regGS("Add new user type","Adauga tip de utilizator");
regGS("Add new article type","Adauga tip de articol");
regGS("Add new country","Adauga tara");
regGS("Add new language","Adauga limba");
regGS("Add new section","Adauga sectiune");
regGS("View logs","");
regGS("Change your password","");
regGS("Your articles","");
regGS("Submitted articles","");
regGS("Quick Menu","Meniu rapid");
regGS("Logs","Loguri");
regGS("There are $1 articles(s) left.","");
regGS("There are $1 issues(s) left.","");
regGS("There are $1 section(s) left.","");
regGS("There are $1 publication(s) left.","");
regGS("There are $1 keywords(s) left.","");
regGS("There are $1 infotypes(s) left.","");
regGS("There are $1 countries left.","");
regGS("Subscription default time","");
regGS("Name<BR><SMALL>(click to edit)</SMALL>","");
regGS("User account","");
regGS("No such user account.","");
regGS("Add new subscription","");
regGS("You do not have the right to add subscriptions.","");
regGS("Adding subscription","");
regGS("The section could not be added.","");
regGS("Delete subscription","");
regGS("You do not have the right to delete subscriptions.","");
regGS("Deleting subscription","");
regGS("No such subscription.","");
regGS("The section $1 could not be deleted.","");
regGS("Yes","Da");
regGS("No","Nu");
regGS("No issues.","Nu exista editii");


?>