<?
regGS("Name<BR><SMALL>(click to see issues)</SMALL>","Nume");
regGS("Delete publication $1","ªterge publicaþia $1");
regGS("No publications.","Nu existã publicaþii");
regGS("Country<BR><SMALL>(click to edit)</SMALL>","Þara<br><font size=-1>(click pt. a edita)</font>");
regGS("Delete entry $1","ªterge înregistrarea $1");
regGS("No entries defined.","Nu existã înregistrãri");
regGS("Change publication information","Modificã informaþia despre publicaþie");
regGS("You do not have the right to edit publication information.","Nu aveþi dreptul de a edita informaþia despre publicaþie");
regGS("Changing publication information","Modific informaþia despre publicaþie");
regGS("You do not have the right to change publication information.","Nu aveþi dreptul de a modifica informaþia despre publicaþie");
regGS("The publication $1 has been successfuly updated.","Publicaþia $1 a fost modificatã cu succes");
regGS("Publication $1 changed","Publicaþia $1 a fost modificatã");
regGS("The publication information could not be updated.","Informaþia despre publicaþie nu poate fi modificatã");
regGS("Please check if another publication with the same or the same site name does not already exist.","Verificaþi dacã nu existã altã publicaþie cu acelaºi nume sau acealºi sit");
regGS("Delete publication","ªterge publicaþia");
regGS("You do not have the right to delete publications.","Nu aveti dreptul sa ºtergeþi publicaþii");
regGS("Are you sure you want to delete the publication $1?","Sînteþi sigur ca doriþi sã ºtergeþi publicaþia $1?");
regGS("Deleting publication","ªterg publicaþia");
regGS("There are $1 image(s) left.","Mai sînt $1 imagini");
regGS("There are $1 subscription(s) left.","Mai sînt $1 subscrieri");
regGS("The publication $1 has been deleted.","Publicaþia $1 a fost ºtearsã");
regGS("The publication $1 could not be deleted.","Publicaþia $1 nu poate fi ºtearsã");
regGS("Publication $1 deleted","Publicaþia $1 a fost ºtearsã");
regGS("Adding new publication","Adaug publicaþie");
regGS("The publication could not be added.","Publicaþia nu poate fi adãugatã");
regGS("Add new country default subscription time","Adaugã timp implicit de subscriere la þarã");
regGS("You do not have the right to manage publications.","Nu aveþi dreptul de a modifica publicaþii");
regGS("Adding new country default subscription time","Adaug timp implicit de subscriere la þarã");
regGS("You must select a country.","Trebuie sã selectaþi o þarã");
regGS("The default subscription time for $1 has been successfuly added.","Timpul implicit de subscriere la þara $1 a fost adãugat cu succes");
regGS("The default subscription time for country $1 could not be added.","Timp implicit de subscriere la þara $1 nu poate fi adãugat");
regGS("Default subscription time for $1 added","Timpul implicit de subscriere la þara $1 a fost adãugat");
regGS("Change subscription default time","Modificã timpul implicit de subscriere la þarã");
regGS("No default time entry for that country.","Nu existã timp implicit de subscriere la þarã");
regGS("Changing default subscription time","Modificã timpul implicit de subscriere la þarã");
regGS("The default subscription time for $1 has been successfuly updated.","Timpul implicit de subscriere la þara $1 a fost modificat cu succes");
regGS("Default subscription time for $1 changed","Timpul implicit de subscriere la þara $1 a fost modificat");
regGS("The default subscription time could not be updated.","Timpul implicit de subscriere nu poate fi modificat");
regGS("Delete subscription default time","ªterge timpul implicit de subscriere");
regGS("Are you sure you want to delete the subscription default time for $1?","Sînteþi sigur cã doriþi sã ºtergeþi timpul implicit de subscriere la þara $1?");
regGS("Deleting subscription default time","ªterg timp implicit de subscriere");
regGS("The subscription default time for $1 has been deleted.","Timpul implicit de subscriere la þara $1 a fost ºters");
regGS("The default subscription time for $1 could not be deleted.","Timpul implicit de subscriere la þara $1 nu poate fi ºters");
regGS("Subscription default time for $1 deleted","Timpul implicit de subscriere la þara $1 a fost ºters");
regGS("Name<BR><SMALL>(click to select the publication)</SMALL>","Nume");
regGS("The publication $1 has been successfuly added.","Publicaþia $1 a fost adãugatã");
regGS("Publication $1 added","Publicaþia $1 a fost adãugatã");

?>