<?
regGS("Name<BR><SMALL>(click to see issues)</SMALL>","Nume<br><font size=-1>(click pt. a vedea editiile)</font>");
regGS("Delete publication $1","Sterge publicatia $1");
regGS("No publications.","Nu exista publicatii");
regGS("Country<BR><SMALL>(click to edit)</SMALL>","Tara<br><font size=-1>(click pt. a edita)</font>");
regGS("Delete entry $1","Sterge inregistrarea $1");
regGS("No entries defined.","Nu exista inregistrari");
regGS("Change publication information","Modifica informatia publicatiei");
regGS("You do not have the right to edit publication information.","");
regGS("Changing publication information","");
regGS("You do not have the right to change publication information.","");
regGS("The publication $1 has been successfuly updated.","");
regGS("Publication $1 changed","Publicatia $1 a fost modificata");
regGS("The publication information could not be updated.","");
regGS("Please check if another publication with the same or the same site name does not already exist.","");
regGS("Delete publication","");
regGS("You do not have the right to delete publications.","");
regGS("Are you sure you want to delete the publication $1?","");
regGS("Deleting publication","");
regGS("There are $1 article(s) left.","");
regGS("There are $1 image(s) left.","");
regGS("There are $1 subscription(s) left.","");
regGS("The publication $1 has been deleted.","");
regGS("The publication $1 could not be deleted.","");
regGS("Publication $1 deleted","");
regGS("Adding new publication","");
regGS("The publication could not be added.","");
regGS("Add new country default subscription time","");
regGS("You do not have the right to manage publications.","");
regGS("Adding new country default subscription time","");
regGS("You must select a country.","");
regGS("The default subscription time for $1 has been successfuly added.","");
regGS("The default subscription time for country $1 could not be added.","");
regGS("Default subscription time for $1 added","");
regGS("Change subscription default time","");
regGS("No default time entry for that country.","");
regGS("Changing default subscription time","");
regGS("The default subscription time for $1 has been successfuly updated.","");
regGS("Default subscription time for $1 changed","");
regGS("The default subscription time could not be updated.","");
regGS("Delete subscription default time","");
regGS("Are you sure you want to delete the subscription default time for $1?","");
regGS("Deleting subscription default time","");
regGS("The subscription default time for $1 has been deleted.","");
regGS("The default subscription time for $1 could not be deleted.","");
regGS("Subscription default time for $1 deleted","");
regGS("Name<BR><SMALL>(click to select the publication)</SMALL>","");
regGS("The publication $1 has been successfuly added.","");
regGS("Publication $1 added","Publicatia $1 a fost adaugata");

?>