<?
regGS("Name<BR><SMALL>(click to see issues)</SMALL>","Ime<br><small>(kliknite da uðete u izdanje)</small>");
regGS("Delete publication $1","Izbi¹i publikaciju $1");
regGS("No publications.","Jo¹ nema nikakvih publikacija");
regGS("Country<BR><SMALL>(click to edit)</SMALL>","Zemlja<br><small>(kliknite na ime zemlje)</small>");
regGS("Delete entry $1","Izbri¹i podatak $1");
regGS("No entries defined.","Nijedan podatak nije definisan");
regGS("Change publication information","Izmeni podatke o publikaciji");
regGS("You do not have the right to edit publication information.","Nemate pravo da menjate podatke o publikacijama.");
regGS("Changing publication information","Izmena podataka o publikaciji");
regGS("You do not have the right to change publication information.","Nemate pravo da menjate podatke o publikacijama.");
regGS("The publication $1 has been successfuly updated.","Publikacija $1 je uspe¹no izmenjena.");
regGS("Publication $1 changed","Publikacija $1 je izmenjena");
regGS("The publication information could not be updated.","Podaci o publikaciji nisu mogli da budu izmenjeni.");
regGS("Please check if another publication with the same or the same site name does not already exist.","Proverite da li sluèajno ne postoji neka druga istoimena publikacija ili istoimeni sajt.");
regGS("Delete publication","Izbri¹i publikaciju");
regGS("You do not have the right to delete publications.","Nemate pravo da bri¹ete publikacije.");
regGS("Are you sure you want to delete the publication $1?","Da li ste sigurni da ¾elite da izbri¹ete publikaciju $1?");
regGS("Deleting publication","Brisanje publikacije");
regGS("There are $1 image(s) left.","Preostala(-lo) je jo¹ $1 slika");
regGS("There are $1 subscription(s) left.","Preostala(-lo) je jo¹ $1 pretplata");
regGS("The publication $1 has been deleted.","Publikacija $1 je izbrisana");
regGS("The publication $1 could not be deleted.","Publikacija $1 nije mogla da bude izbrisana.");
regGS("Publication $1 deleted","Publikacija $1 je izbrisana");
regGS("Adding new publication","Dodavanje nove publikacije");
regGS("The publication could not be added.","Publikacija nije mogla da bude dodata.");
regGS("Add new country default subscription time","Dodajte novo standardno trajanje pretplate za datu zemlju");
regGS("You do not have the right to manage publications.","Nemate pravo da manipuli¹ete publikacijama");
regGS("Adding new country default subscription time","Dodavanje novog standardnog trajanja pretlate za datu zemlju");
regGS("You must select a country.","Morate odabrati zemlju");
regGS("The default subscription time for $1 has been added.","Standardno trajanje pretplate je uspe¹no dodato za zemlju: $1");
regGS("The default subscription time for country $1 could not be added.","Standardno trajanje pretplate nije moglo da bude dodato za zemlju: $1 ");
regGS("Change subscription default time","Izmeni standardno trajanje pretplate");
regGS("No default time entry for that country.","Standardno trajanje pretplate nije definisano za tu zemlju.");
regGS("Changing default subscription time","Izmena standardnog trajanja pretplate");
regGS("The default subscription time for $1 has been successfuly updated.","Standardno trajanje pretplate za publikaciju $1 je uspe¹no izmenjeno.");
regGS("Default subscription time for $1 changed","Standardno trajanje pretplate za publikaciju $1 je izmenjeno");
regGS("The default subscription time could not be updated.","Standardno trajanje pretplate nije moglo da bude izmenjeno.");
regGS("Delete subscription default time","Izbri¹i standardno trajanje pretplate");
regGS("Are you sure you want to delete the subscription default time for $1?","Da li ste sigurni da ¾elite da izbri¹ete standardno trajanje pretplate za publikaciju $1");
regGS("Deleting subscription default time","Brisanje standardnog trajanje pretplate");
regGS("The subscription default time for $1 has been deleted.","Standardno trajanje pretplate za publikaciju $1 je izbrisano.");
regGS("The default subscription time for $1 could not be deleted.","Standardno trajanje pretplate za publikaciju $1 nije moglo da budeizbrisano");
regGS("Subscription default time for $1 deleted","Standardno trajanje pretplate za publikaciju $1 je izbrisano");
regGS("Name<BR><SMALL>(click to select the publication)</SMALL>","Ime<br><small>(kliknite da uðete u publikaciju)</small>");
regGS("The publication $1 has been successfuly added.","Publikacija $1 je uspe¹no dodata");
regGS("Publication $1 added","Publikacija $1 je dodata");

?>
