#!/bin/sh

rm -f $BIN_DIR/notifyendsubs
rm -f $BIN_DIR/notifyevents
rm -f $CONF_DIR/smtp.conf
. ${INSTALL_CONF}/cron_functions
if [ -f /etc/crontab ]; then
    uninstall_cron_task "$BIN_DIR/notifyendsubs" /etc/crontab
    uninstall_cron_task "$BIN_DIR/notifyevents" /etc/crontab
fi
uninstall_cron_task "$BIN_DIR/notifyendsubs" /etc/cron.d/campsite_subs -d || exit 1
uninstall_cron_task "$BIN_DIR/notifyevents" /etc/cron.d/campsite_events -d || exit 1
restart_cron
exit 0
