<?

regGS("User management","Evidenþa utilizatorilor");
regGS("Set","Actualizeazã");
regGS("Update","Modificã");
regGS("Rights","Drepturi");
regGS("IP Access","Acces bazat pe adresa IP");
regGS("User Name","Nume utilizator");
regGS("Full Name","Nume");
regGS("Staff","Personal");
regGS("Delete user $1","ªterge utilizatorul $1");
regGS("You do not have the right to create user accounts.","Nu aveþi dreptul sã creaþi conturi de utilizatori");
regGS("Title","Titlu");
regGS("Gender","Sex");
regGS("Mr.","Dl.");
regGS("Mrs.","Dna.");
regGS("Ms.","Dra.");
regGS("Dr.","Dr.");
regGS("Male","Masculin");
regGS("Female","Feminin");
regGS("under 18","sub 18");
regGS("65 or over","65 sau mai mult");
regGS("Age","Vârsta");
regGS("Confirm password","Confirmare parolã");
regGS("E-Mail","E-Mail");
regGS("City","Localitate");
regGS("Street Address","Adresa");
regGS("Postal Code","Cod Poºtal");
regGS("State","Stat");
regGS("Phone","Telefon");
regGS("Fax","Fax");
regGS("Contact Person","Persoanã de contact");
regGS("Second Phone","Al doilea telefon");
regGS("Employer","Angajator");
regGS("Employer Type","Tipul angajatorului");
regGS("Corporate","Corporaþie");
regGS("Non-Governmental Organisation","Organizaþie non-guvernamentalã");
regGS("Government Agency","Agenþie guvernamentalã");
regGS("Academic","Academic");
regGS("Media","Media");
regGS("Position","Poziþia");
regGS("Adding new user account","Adaug cont utilizator");
regGS("You must select a $1","Trebuie sã selectaþi $1");
regGS("The password must be at least 6 characters long and both passwords should match.","Parola trebuie sã conþinã cel puþin 6 caractere ºi ambele parole trebuie sã fie identice");
regGS("You must select an user type.","Trebuie sã selectaþi un tip de utilizator");
regGS("The user account $1 has been created.","Contul de utilizator $1 a fost creat");
regGS("The user account could not be created.","Contul de utilizator nu poate fi creat");
regGS("Please check if an account with the same user name does not already exist.","Verificaþi dacã un cont cu acelaºi nume de utilizator existã deja");
regGS("User account $1 created","Contul de utilizator $1 a fost creat");
regGS("Change user password","Schimbã parola");
regGS("You do not have the right to change user passwords.","Nu aveþi dreptul sã schimbaþi parola utilizatorului");
regGS("Changing user password","Schimb parola");
regGS("The password could not be changed.","Parola nu poate fi schimbatã");
regGS("Password changed for $1","Parola a fost schimbatã pentru $1");
regGS("The password has been changed.","Parola a fost schimbatã");
regGS("User may manage templates","Utilizatorul are dreptul sã þinã evidenþa ºabloanelor");
regGS("User may add/change country entries","Utilizatorul are dreptul sã adauge/modifice þãri");
regGS("Edit user account permissions","Modificã drepturile contului de utilizator");
regGS("You do not have the right to change user account permissions.","Nu aveþi dreptul sã modificaþi drepturile contului de utilizator");
regGS("This user account does not have permissions information.","Nu existã drepturi pentru acest cont de utilizator");
regGS("Updating user account permissions","Modific drepturile contului");
regGS("Permissions for $1 changed","Drepturile pentru contul $1 au fost modificate");
regGS("User account permissions have been successfuly updated.","Drepturile pentru contul de utilizator au fost modificate");
regGS("User account permissions could not be updated.","Drepturile pentru contul de utilizator nu pot fi modificate");
regGS("Change user account information","Modifica informaþiile despre contul de utilizator");
regGS("You do not have the right to change user account information.","u aveþi dreptul sã modificaþi informaþiile despre contul de utilizator");
regGS("Changing user account information","Modific informaþiile despre contul de utilizator");
regGS("User account information has been changed.","Informaþiile despre contul de utilizator au fost modificate");
regGS("User account information could not be changed.","Informaþiile despre contul de utilizator nu pot fi modificate");
regGS("User account information changed for $1","Informaþiile despre contul de utilizator $1 au fost modificate");
regGS("Old password","Parola veche");
regGS("New password","Parola nouã");
regGS("Confirm new password","Confirmare parola nouã");
regGS("Changing your password","Schimb parola");
regGS("The password you typed is incorrect.","Parola introdusã e incorectã");
regGS("User $1 changed his password","Utilizatorul $1 ºi-a schimbat parola");
regGS("Delete user account","ªterge contul de utilizator");
regGS("You do not have the right to delete user accounts.","Nu aveþi dreptul sã ºtergeþi conturi de utilizatori");
regGS("Are you sure you want to delete the user account $1 ?","Doriþi sã ºtergeþi contul $1?");
regGS("Deleting user account","ªterg contul de utilizator");
regGS("The user account $1 has been deleted.","Contul de utilizator $1 a fost ºters");
regGS("The user account $1 could not be deleted.","Contul de utilizator $1 nu poate fi ºters");
regGS("No such user.","Utilizatorul nu existã");
regGS("User IP access list management","Evidenþa listei de acces bazat pe adresa IP");
regGS("Add new IP address group","Adaugã grup de adrese IP");
regGS("No records.","Nu existã inregistrãri");
regGS("Delete IP Group $1","ªterge grupul de adrese IP $1");
regGS("You do not have the right to add IP address groups.","Nu aveþi dreptul sã adãugaþi grupuri de adrese IP");
regGS("Start IP","Adresa IP de start");
regGS("Number of addresses","Numãrul de adrese IP");
regGS("IP Access List","Lista de acces bazatã pe adrese IP");
regGS("Adding new IP Group","Adaug grup de adrese IP");
regGS("The IP Group $1 has been created.","Grupul de adrese IP $1 a fost adãugat");
regGS("IP Group $1 added for user $2","Grupul de adrese IP $1 a fost adãugat la utilizatorul $2");
regGS("The IP Group could not be created.","Grupul de adrese IP nu poate fi adãugat");
regGS("Please check if an account with the same IP Group does not already exist.","Verificaþi dacã un cont cu acelaºi grup de adrese IP existã deja");
regGS("Delete IP Group","ªterge grupul de adrese IP");
regGS("You do not have the right to delete IP Groups.","Nu aveþi dreptul sã ºtergeþi grupuri de adrese IP");
regGS("Are you sure you want to delete the IP Group $1?","Doriþi sã ºtergeþi grupul de adrese IP $1?");
regGS("No such IP Group.","Grupul de adrese IP nu existã");
regGS("Deleting IP Group","ªterg grupul de adrese IP");
regGS("The IP address group $1 has been deleted.","Grupul de adrese IP $1 a fost ºters");
regGS("The IP Group could not be deleted.","Grupul de adrese IP nu poate fi ºters");


?>
