<?

regGS("User management","BenutzerInnen managen");
regGS("Set","Auswählen");
regGS("Update","Aktualisieren");
regGS("Rights","Berechtigungen");
regGS("IP Access","IP Zugang");
regGS("User Name","Benutzername");
regGS("Full Name","Vollständiger Name");
regGS("Staff","Personal");
regGS("Delete user $1","BenutzerInn $1 löschen");
regGS("You do not have the right to create user accounts.","Keine Berechtigung Benutzerkonten zu erstellen");
regGS("Full name","Vollständiger Name");
regGS("Title","Titel");
regGS("Gender","Geschlecht");
regGS("Mr.","Herr");
regGS("Mrs.","Frau");
regGS("Ms.","Frau");
regGS("Dr.","Dr.");
regGS("Male","männlich");
regGS("Female","weiblich");
regGS("under 18","unter 18");
regGS("65 or over","65 oder älter");
regGS("Age","Alter");
regGS("Confirm password","Passwort bestätigen");
regGS("E-Mail","E-Mail");
regGS("City","Stadt");
regGS("Street Address","Strasse");
regGS("Postal Code","Postleitzahl");
regGS("State","Staat");
regGS("Phone","Telefonnummer");
regGS("Fax","Fax");
regGS("Contact Person","Kontaktperson");
regGS("Second Phone","Zweite Telefonnummer");
regGS("Employer","Arbeitgeber");
regGS("Employer Type","Arbeitsfeld");
regGS("Corporate","Firma");
regGS("Non-Governmental Organisation","Nichtstaatliche Organisation");
regGS("Government Agency","Staatliche Stelle");
regGS("Academic","Akademiker");
regGS("Media","Medien");
regGS("Position","Stellung");
regGS("Adding new user account","Neues Benutzerkonto hinzufügen");
regGS("ou do not have the right to create user accounts.","Keine Berechtigung Benutzerkonten zu erstellen");
regGS("You must select a $1","Bitte ein $1 auswählen");
regGS("The password must be at least 6 characters long and both passwords should match.","Das Passwort muss mindestens 6 Stellen lang sein und beide Passwörter müssen übereinstimmen");
regGS("You must select an user type.","Bitte Benutzertyp auswählen");
regGS("The user account $1 has been created.","Benutzerkonto $1 wurde erstellt");
regGS("The user account could not be created.","Benutzerkonto konnte nicht erstellt werden");
regGS("Please check if an account with the same user name does not already exist.","Bitte überprüfen, ob ein Konto mit demselben Benutzername existiert");
regGS("User account $1 created","Benutzerkonto $1 erstellt");
regGS("User account $1 added","Benutzerkonto $1 hinzugefügt");
regGS("Change user password","Benutzerpasswort ändern");
regGS("You do not have the right to change user passwords.","Keine Berechtigung Benutzerpasswörter zu ändern");
regGS("Changing user password","Passwort wird geändert");
regGS("The password could not be changed.","Das Passwort konnte nicht geändert werden");
regGS("Password changed for $1","Passwort für $1 geändert");
regGS("The password has been changed.","Passwort wurde geändert");
regGS("User may manage templates","BenutzerIn kann Templates managen");
regGS("User may add/change country entries","BenutzerIn kann Ländereinträge hinzufügen/ändern");
regGS("Edit user account permissions","Benutzerkontogenehmigung bearbeiten");
regGS("You do not have the right to change user account permissions.","Keine Berechtigung Benutzerkontogenehmigung zu ändern");
regGS("This user account does not have permissions information.","Dieses Benutzerkonto hat keine Genehmigungsinformationen");
regGS("Updating user account permissions","Benutzerkontogenehmigung wird aktualisiert");
regGS("Permissions for $1 changed","Genehmigung für $1 geändert");
regGS("User account permissions have been successfuly updated.","Benutzerkontogenehmigung erfolgreich aktualisiert");
regGS("User account permissions could not be updated.","Benutzerkontogenehmigung konnte nicht aktualisiert werden");
regGS("Change user account information","Benutzerkontoinformation ändern");
regGS("You do not have the right to change user account information.","Keine Berechtigung Benutzerkontoinformation zu ändern");
regGS("Changing user account information","Benutzerkontoinformation wird geändert");
regGS("User account information has been changed.","Benutzerkontoinformation geändert");
regGS("User account information could not be changed.","Benutzerkontoinformation konnte nicht geändert werden");
regGS("User account information changed for $1","Benutzerkontoinformation für $1 wurde geändert");
regGS("Old password","Altes Passwort");
regGS("New password","Neues Passwort");
regGS("Confirm new password","Neues Passwort bestätogen");
regGS("Changing your password","Passwort wird geändert");
regGS("The password you typed is incorrect.","Das eingegebene Passwort ist falsch");
regGS("The password has been changed successfully.","Passwort erfolgreich geändert");
regGS("User $1 changed his password","BenutzerIn $1 hat Passwort geändert");
regGS("Delete user account","Benutzerkonto löschen");
regGS("You do not have the right to delete user accounts.","Keine Berechtigung Benutzerkonten zu löschen");
regGS("Are you sure you want to delete the user account $1 ?","Benutzerkonto $1 wirklich löschen?");
regGS("Deleting user account","Benutzerkonto wird gelöscht");
regGS("User account $1 deleted","Benutzerkonto $1 gelöscht");
regGS("The user account $1 has been deleted.","Benutzerkonto $1 wurde gelöscht");
regGS("The user account $1 could not be deleted.","Benutzerkonto $1 konnte nicht gelöscht werden");
regGS("No such user.","BenutzerIn existiert nicht");
regGS("User IP access list management","Zugang der Benutzer-IPs managen");
regGS("Add new IP address group","Neue IP-Adressengruppe hinzufügen");
regGS("No records.","Keine Eintragungen");
regGS("Delete IP Group $1","IP-Gruppe $1 löschen");
regGS("Add new IP Group","Neue IP-Gruppe hinzufügen");
regGS("You do not have the right to add IP groups.","Keine Berechtigung IP-Gruppen hinzuzufügen");
regGS("Start IP","IP starten");
regGS("Number of addresses","Anzahl der Adressen");
regGS("IP Access List","IP-Zugangsliste");
regGS("Adding new IP Group","Neue IP-Gruppe wird hinzugeführt");
regGS("You do not have the right to add IP Groups.","Keine Berechtigung IP-Gruppen hinzuzufügen");
regGS("IP access list","IP-Zugangsliste");
regGS("The IP Group $1 has been created.","IP-Gruppe $1 wurde erstellt");
regGS("IP Group $1 added for user $2","IP-Gruppe $1 wurde für BenutzerIn $2 hinzugefügt");
regGS("The IP Group could not be created.","IP-Gruppe konnte nicht erstellt werden");
regGS("Please check if an account with the same IP Group does not already exist.","Bitte überprüfen, ob bereits ein Konto mit derselben IP-Gruppe existiert");
regGS("Delete IP Group","IP-Gruppe löschen");
regGS("You do not have the right to delete IP Groups.","Keine Berechtigung IP-Gruppen zu löschen");
regGS("Are you sure you want to delete the IP Group $1?","IP-Gruppe $1 wirklich löschen");
regGS("No such IP Group.","IP-Gruppe nicht vorhanden");
regGS("Deleting IP Group","IP-Gruppe wird gelöscht");
regGS("IP Group $1 deleted","IP-Gruppe $1 gelöscht");
regGS("The IP Group $1 has been deleted.","IP-Gruppe $1 wurde gelöscht");
regGS("The IP Group could not be deleted.","IP-Gruppe konnte nicht gelöscht werden");


?>