<?
regGS("User management","Správa u¾ivatelù");
regGS("Set","Nastavit");
regGS("Update","Obnovit");
regGS("Rights","Práva");
regGS("IP Access","IP pøístup");
regGS("User Name","U¾ivatelské jméno");
regGS("Full Name","Jméno");
regGS("Staff","Zamìstnanci");
regGS("Delete user $1","Smazat u¾ivatele $1");
regGS("You do not have the right to create user accounts.","Nemáte právo vytváøet u¾ivatelské úèty");
regGS("Full name","Jméno");
regGS("Title","Titul");
regGS("Gender","Pohlaví");
regGS("Mr.","p.");
regGS("Mrs.","pí");
regGS("Ms.","sl.");
regGS("Dr.","Dr.");
regGS("Male","Mu¾");
regGS("Female","®ena");
regGS("under 18","do 18 let");
regGS("65 or over","65 a více");
regGS("Age","Vìk");
regGS("Confirm password","Potvrïte heslo");
regGS("E-Mail","E-mail");
regGS("City","Mìsto");
regGS("Street Address","Ulice");
regGS("Postal Code","PSÈ");
regGS("State","Zemì");
regGS("Phone","Telefon");
regGS("Fax","Fax");
regGS("Contact Person","Kontaktní osoba");
regGS("Second Phone","Dal¹í telefon");
regGS("Employer","Zamìstnavatel");
regGS("Employer Type","Druh organizace");
regGS("Corporate","Korporace");
regGS("Non-Governmental Organisation","Nevládní organizace");
regGS("Government Agency","Vládní agentura");
regGS("Academic","Univerzitní oblast");
regGS("Media","Média");
regGS("Position","Pozice");
regGS("Adding new user account","Pøidání nového u¾ivatelského úètu");
regGS("You must select a $1","Musíte vybrat $1");
regGS("The password must be at least 6 characters long and both passwords should match.","Heslo musí obsahovat nejménì 6 znakù a obì hesla musí být shodná");
regGS("You must select an user type.","Musíte zvolit typ u¾ivatele");
regGS("The user account $1 has been created.","U¾ivatelský úèet $1 byl vytvoøen");
regGS("The user account could not be created.","U¾ivatelský úèet $1 nemohl být vytvoøen");
regGS("Please check if an account with the same user name does not already exist.","Prosím zkontrolujte, zda úèet se stejným u¾ivatelským jménem ji¾ neexistuje");
regGS("User account $1 created","U¾ivatelský úèet $1 byl vytvoøen");
regGS("User account $1 added","U¾ivatelský úèet $1 byl pøidán");
regGS("Change user password","Zmìnit u¾ivatelské heslo");
regGS("You do not have the right to change user passwords.","Nemáte právo mìnit u¾ivatelská hesla");
regGS("Changing user password","Zmìna u¾ivatelského hesla");
regGS("The password could not be changed.","Heslo nemohlo být zmìnìno");
regGS("Password changed for $1","Heslo bylo zmìnìno na $1");
regGS("The password has been changed.","Heslo bylo zmìnìno");
regGS("User may manage templates","U¾ivatel mù¾e spravovat ¹ablony");
regGS("User may add/change country entries","U¾ivatel mù¾e pøidat/zmìnit polo¾ky zemí");
regGS("Edit user account permissions","Editovat práva u¾ivatelského úètu");
regGS("You do not have the right to change user account permissions.","Nemáte právo mìnit práva u¾ivatelského úètu");
regGS("This user account does not have permissions information.","Tento u¾ivatelský úèet nemá informace o právech");
regGS("Updating user account permissions","Obnova práv u¾ivatelského úètu");
regGS("Permissions for $1 changed","Práva pro $1 byla zmìnìna");
regGS("User account permissions have been successfuly updated.","Práva u¾ivatelského úètu byla úspì¹nì obnovena");
regGS("User account permissions could not be updated.","Práva u¾ivatelského úètu nemohla být obnovena");
regGS("Change user account information","Zmìnit informace u¾ivatelského úètu");
regGS("You do not have the right to change user account information.","Nemáte právo mìnit informace u¾ivatelského úètu");
regGS("Changing user account information","Zmìna informací u¾ivatelského úètu");
regGS("User account information has been changed.","Informace u¾ivatelského úètu byly zmìnìny");
regGS("User account information could not be changed.","Informace u¾ivatelského úètu nemohly být zmìnìny");
regGS("User account information changed for $1","Informace u¾ivatelského úètu byly zmìnìny pro $1");
regGS("Old password","Staré heslo");
regGS("New password","Nové heslo");
regGS("Confirm new password","Potvrïte nové heslo");
regGS("Changing your password","Zmìnit heslo");
regGS("The password you typed is incorrect.","Heslo, které jste zadali je ¹patné");
regGS("The password has been changed successfully.","Heslo bylo úspì¹nì zmìnìno");
regGS("User $1 changed his password","U¾ivatel $1 zmìnil své heslo");
regGS("Delete user account","Smazat u¾ivatelský úèet");
regGS("You do not have the right to delete user accounts.","Nemáte právo smazat u¾ivatelské úèty");
regGS("Are you sure you want to delete the user account $1 ?","Urèitì chcete smazat u¾ivatelský úèet $1?");
regGS("Deleting user account","Mazání u¾ivatelského úètu");
regGS("User account $1 deleted","U¾ivatelský úèet $1 byl smazán");
regGS("The user account $1 has been deleted.","U¾ivatelský úèet $1 byl smazán");
regGS("The user account $1 could not be deleted.","U¾ivatelský úèet $1 nemohl být smazán");
regGS("No such user.","U¾ivatel neexistuje");
regGS("User IP access list management","Správa seznamu u¾ivatelských IP pøístupù");
regGS("Add new IP address group","Pøidat novou skupinu IP adres");
regGS("No records.","®ádný záznam");
regGS("Delete IP Group $1","Smazat IP skupinu $1 ");
regGS("Add new IP Group","Pøidat novou IP skupinu");
regGS("You do not have the right to add IP groups.","Nemáte právo pøidat IP skupiny");
regGS("Start IP","Poèáteèní IP adresa");
regGS("Number of addresses","Poèet adres");
regGS("IP Access List","Seznam IP pøístupù");
regGS("Adding new IP Group","Pøidání nové IP skupiny");
regGS("You do not have the right to add IP Groups.","Nemáte právo pøidat IP skupiny");
regGS("IP access list","Seznam IP pøístupù");
regGS("The IP Group $1 has been created.","IP skupina $1 byla vytvoøena");
regGS("IP Group $1 added for user $2","IP skupiny $1  byla pøidána pro u¾ivatele $2");
regGS("The IP Group could not be created.","IP skupina nemohla být vytvoøena");
regGS("Please check if an account with the same IP Group does not already exist.","Zkontrolujte prosím, zda ji¾ neexistuje úèet se stejnou IP skupinou");
regGS("Delete IP Group","Smazat IP skupinu");
regGS("You do not have the right to delete IP Groups.","Nemáte právo smazat IP skupinu");
regGS("Are you sure you want to delete the IP Group $1?","Urèitì chcete smazat IP skupinu $1?");
regGS("No such IP Group.","IP skupina neexistuje");
regGS("Deleting IP Group","Mazání IP skupiny");
regGS("IP Group $1 deleted","IP skupina $1 byla smazána");
regGS("The IP Group $1 has been deleted.","IP skupina $1 byla smazána");
regGS("The IP Group could not be deleted.","IP skupina nemohla být smazána");

?>