<?

regGS("Name<BR><SMALL>(click to see sections)</SMALL>","Nume");
regGS("Front Page Template<BR><SMALL>(click to change)</SMALL>","ªablonul paginii principale");
regGS("Single Article Template<BR><SMALL>(click to change)</SMALL>","ªablonul pentru afiºarea articolelor");
regGS("Published<BR><SMALL>(yyyy-mm-dd)</SMALL>","Publicat");
regGS("Delete issue $1","ªterge ediþia $1");
regGS("Change issue status","Modificã starea ediþiei");
regGS("You do not have the right to change issues.","Nu aveþi dreptul de a modifica ediþia");
regGS("Are you sure you want change the issue $1 status from $2 to $3?","Doriþi sã schimbaþi starea ediþiei $1 de la $2 la $3?");
regGS("Changing issue status","Modific starea ediþiei");
regGS("Status of the issue $1 has been changed from $2 to $3","Starea ediþiei $1 a fost schimbatã de la $2 la $3");
regGS("Issue $1 Published: $2  changed status","Starea ediþiei $1 publicatã în $2 a fost modificatã");
regGS("Status of the issue $1 could not be changed.","Starea ediþiei $1 nu poate fi schimbatã");
regGS("Add new translation","Adaugã traducere");
regGS("You do not have the right to add issues.","Nu aveþi dreptul sã adãugaþi ediþii");
regGS("The issue $1 has been successfuly added.","Ediþia $1 a fost creeatã cu succes");
regGS("The issue could not be added.","Ediþia nu poate fi creatã");
regGS("Please check if another issue with the same number/language does not already exist.","Verificaþi dacã altã ediþie cu acelaºi numãr/aceeaºi limbã existã");
regGS("Issue $1 added","Ediþia $1 a fost adãugatã");
regGS("Change issue details","Modificã ediþia");
regGS("You do not have the right to change issue details.","Nu aveþi dreptul sã modificaþi ediþia");
regGS("Updating issue","Modific ediþia");
regGS("Changing issue's details","Modific ediþia");
regGS("The issue $1 has been successfuly changed.","Ediþia $1 a fost modificatã cu succes");
regGS("The issue could not be changed.","Ediþia nu poate fi modificatã");
regGS("Issue $1 updated in publication $2","Ediþia $1 a fost modificatã");
regGS("Delete issue","ªterge ediþia");
regGS("You do not have the right to delete issues.","Nu aveþi dreptul sã ºtergeþi ediþia");
regGS("Are you sure you want to delete the issue $1?","Doriþi sã ºtergeþi ediþia $1?");
regGS("Deleting issue","ªterg ediþia");
regGS("The issue $1 has ben deleted.","Ediþia $1 a fost ºtearsã");
regGS("The issue $1 could not be deleted.","Ediþia $1 nu poate fi ºtearsã");
regGS("All sections from Issue $1 from publication $2 deleted","Toate secþiunile din ediþia $1 din publicaþia $2 au fost ºterse");
regGS("Issue $1 from publication $2 deleted","Ediþia $1 din publicaþia $2 a fost ºtearsã");
regGS("Use the structure of the previous issue","Foloseºte structura ediþiei anterioare");
regGS("Copy the entire structure in all languages from the previous issue except for content.","Copiazã întreaga structurã din ediþia precedentã cu excepþia conþinutului");
regGS("You may modify it later if you wish.","Puteþi sã faceþi modificarea mai târziu");
regGS("Create a new structure","Creazã o structurã nouã");
regGS("Create a complete new structure.","Creazã o structurã nouã");
regGS("You must define an issue type for each language and then sections for them.","");
regGS("Copy previous issue","Copiazã ediþia precedentã");
regGS("No previous issue.","Nu existã ediþie anterioarã");
regGS("Copy structure from issue nr $1","Copiazã structura de la ediþia nr $1");
regGS("Copying previous issue","Copiez ediþia anterioarã");
regGS("Copying done.","Copierea terminatã cu succes");
regGS("New issue $1 from $2 in publication $3","Ediþia nouã $1 din $2 în publicaþia $3");
regGS("Adding new issue","Adaug ediþie nouã");
regGS("Issue $1 added in publication $2","Ediþia $1 a fost adãugatã în publicaþia $2");
regGS("Preview issue","Vizualizare ediþie");
regGS("This issue cannot be previewed. Please make sure it has a $1 template selected.","Ediþia nu poate fi vizualizatã. Verificaþi dacã ºablonul paginii principale a fost specificat.");
regGS("front page","pagina principalã");
regGS("Changing issue template","Modific ºablonul ediþiei");
regGS("You do not have the right to change issue templates.","Nu aveþi dreptul sã modificaþi ºablonul ediþiei");
regGS("Changing issue template for front page","Modific ºablonul pentru pagina principalã a ediþiei");
regGS("Changing issue template for single article","Modific ºablonul pentru afiºarea articolului");
regGS("The template has been successfully changed.","ªablonul a fost modificat cu succes");
regGS("Issue template for publication $1 changed to $2","ªablonul ediþiei din publicaþia $1 a fost schimbat la $2");
regGS("Issue template for single articles from $1 changed to $2","ªablonul pentru afiºarea articolului din publicaþia $1 a fost schimbat la $2");
regGS("The template could not be changed.","ªablonul nu poate fi schimbat");


?>