<?
regGS("Name<BR><SMALL>(click to see sections)</SMALL>","Ime<br><small>(kliknite da uðete u rubriku)</small>");
regGS("Front Page Template<BR><SMALL>(click to change)</SMALL>","©ablon za glavnu stranicu<br><small>(kliknite da promenite)</small>");
regGS("Single Article Template<BR><SMALL>(click to change)</SMALL>","©ablon za èlanak<br><small>(kliknite da promenite)</small>");
regGS("Published<BR><SMALL>(yyyy-mm-dd)</SMALL>","Objavljeno<br><small>(gggg-mm-dd)</small>");
regGS("Delete issue $1","Izbri¹i izdanje $1");
regGS("Change issue status","Promeni status izdanja");
regGS("You do not have the right to change issues.","Nemate pravo da menjate izdanja.");
regGS("Are you sure you want change the issue $1 status from $2 to $3?","Da li ste sigurni da ¾elite da promenite status izdanja $1 sa $2 na $3?");
regGS("Changing issue status","Menjanje statusa izdanja");
regGS("Status of the issue $1 has been changed from $2 to $3","Status izdanja $1 je promenjen sa $2 na $3");
regGS("Issue $1 Published: $2  changed status","Izdanje $1 objavljeno: $2 je promenilo status");
regGS("Status of the issue $1 could not be changed.","Status izdanja $1 nije mogao da bude promenjen");
regGS("Add new translation","Dodaj verziju na drugom jeziku");
regGS("You do not have the right to add issues.","Nemate pravo da dodajete izdanja.");
regGS("The issue $1 has been successfuly added.","Izdanje $1 je uspe¹no dodato.");
regGS("The issue could not be added.","Izdanje nije moglo da bude dodato.");
regGS("Please check if another issue with the same number/language does not already exist.","Proverite da izdanje sa istim brojem/na istom jeziku veæ ne postoji.");
regGS("Issue $1 added","Izdanje $1 je dodato");
regGS("Change issue details","Izmeni podrobnosti o izdanju");
regGS("You do not have the right to change issue details.","Nemate pravo da menjate podrobnosti o izdanju");
regGS("Updating issue","Aktuelizacija izdanja");
regGS("Changing issue's details","Izmena podrobnosti o izdanju");
regGS("The issue $1 has been successfuly changed.","Izdanje $1 je uspe¹no promenjeno");
regGS("The issue could not be changed.","Izdanje nije moglo da bude promenjeno");
regGS("Issue $1 updated in publication $2","Izdanje $1 je aktuelizovano u publikaciji $2");
regGS("Delete issue","Izbri¹i izdanje");
regGS("You do not have the right to delete issues.","Nemate pravo da bri¹ete izdanja.");
regGS("Are you sure you want to delete the issue $1?","Da li ste sigurni da ¾elite da izbri¹ete izdanje $1?");
regGS("Deleting issue","Brisanje izdanja");
regGS("The issue $1 has ben deleted.","Izdanje $1 je izbrisano.");
regGS("The issue $1 could not be deleted.","Izdanje $1 nije moglo da bude izbrisano.");
regGS("All sections from Issue $1 from publication $2 deleted","Sve rubrike iz izdanja $1 u publikaciji $2 su izbrisane");
regGS("Issue $1 from publication $2 deleted","Izdanje $1 u publikaciji $2 je izbrisano");
regGS("Use the structure of the previous issue","Upotrebi strukturu prethodnog izdanja");
regGS("Copy the entire structure in all languages from the previous issue except for content.","Prekopiraj èitavu strukturu prethodnog izdanja, na svim jezicima, ali bez sadr¾ine.");
regGS("You may modify it later if you wish.","Ovo mo¾ete izmeniti kasnije, ukoliko budete ¾eleli");
regGS("Create a new structure","Napravi novu strukturu");
regGS("Create a complete new structure.","Napravi potpuno novu strukturu");
regGS("You must define an issue type for each language and then sections for them.","Morate definisati vrstu izdanja za svaki jezik, kao i rubrike za ista");
regGS("Copy previous issue","Prekopiraj prethodno izdanje");
regGS("No previous issue.","Prethodno izdanje ne postoji.");
regGS("Copy structure from issue nr $1","Iskoristi strukturu izdanja br. $1");
regGS("Copying previous issue","Kopiranje prethodnog izdanja");
regGS("Copying done.","Kopiranje je zavr¹eno.");
regGS("New issue $1 from $2 in publication $3","Novo izdanje $1 od $2 u publikaciji $3");
regGS("Adding new issue","Dodavanje novog izdanja");
regGS("Issue $1 added in publication $2","Izdanje $1 je dodato u publikaciji $2");
regGS("Preview issue","Vidi kako izgleda");
regGS("This issue cannot be previewed. Please make sure it has a $1 template selected.","Nije moguæe videti kako æe ovo izdanje izgledati. Proverite da li je ¹ablon $1 selektovan");
regGS("front page","naslovnu strana");
regGS("Changing issue template","Izmena ¹ablona za izdanje");
regGS("You do not have the right to change issue templates.","Nemate pravo da menjate ¹ablone za izdanja");
regGS("Changing issue template for front page","Izmena ¹ablona za naslovnu stranu izdanja");
regGS("Changing issue template for single article","Izmena ¹ablona za pojedinaène èlanke u izdanju");
regGS("The template has been successfully changed.","©ablon je uspe¹no promenjen.");
regGS("Issue template for publication $1 changed to $2","©ablon izdanja za publikaciju $1 je promenjen na $2");
regGS("Issue template for single articles from $1 changed to $2","©ablon za pojedinaène èlanke u izdanju je promenjen sa $1 na $2");
regGS("The template could not be changed.","©ablon nije bilo moguæe promeniti");

?>