<?

regGS("Name<BR><SMALL>(click to see sections)</SMALL>","Nume");
regGS("Front Page Template<BR><SMALL>(click to change)</SMALL>","");
regGS("Single Article Template<BR><SMALL>(click to change)</SMALL>","");
regGS("Published<BR><SMALL>(yyyy-mm-dd)</SMALL>","Publicat");
regGS("Delete issue $1","ªterge ediþia $1");
regGS("Change issue status","Modificã starea ediþiei");
regGS("You do not have the right to change issues.","Nu aveþi dreptul de a modifica ediþia");
regGS("Are you sure you want change the issue $1 status from $2 to $3?","");
regGS("Changing issue status","");
regGS("Status of the issue $1 has been changed from $2 to $3","");
regGS("Issue $1 Published: $2  changed status","");
regGS("Status of the issue $1 could not be changed.","");
regGS("Add new translation","");
regGS("You do not have the right to add issues.","");
regGS("The issue $1 has been successfuly added.","");
regGS("The issue could not be added.","");
regGS("Please check if another issue with the same number/language does not already exist.","");
regGS("Issue $1 added","");
regGS("Change issue details","");
regGS("You do not have the right to change issue details.","");
regGS("Updating issue","");
regGS("Changing issue's details","");
regGS("The issue $1 has been successfuly changed.","");
regGS("The issue could not be changed.","");
regGS("Issue $1 updated in publication $2","");
regGS("Delete issue","");
regGS("You do not have the right to delete issues.","");
regGS("Are you sure you want to delete the issue $1?","");
regGS("Deleting issue","");
regGS("The issue $1 has ben deleted.","");
regGS("The issue $1 could not be deleted.","");
regGS("All sections from Issue $1 from publication $2 deleted","");
regGS("Issue $1 from publication $2 deleted","");
regGS("Use the structure of the previous issue","");
regGS("Copy the entire structure in all languages from the previous issue except for content.","");
regGS("You may modify it later if you wish.","");
regGS("Create a new structure","");
regGS("Create a complete new structure.","");
regGS("You must define an issue type for each language and then sections for them.","");
regGS("Copy previous issue","");
regGS("No previous issue.","");
regGS("Copy structure from issue nr $1","");
regGS("Copying previous issue","");
regGS("Copying done.","");
regGS("New issue $1 from $2 in publication $3","");
regGS("Adding new issue","");
regGS("Issue $1 added in publication $2","");
regGS("Preview issue","");
regGS("This issue cannot be previewed. Please make sure it has a $1 template selected.","");
regGS("front page","");
regGS("Changing issue template","");
regGS("You do not have the right to change issue templates.","");
regGS("Changing issue template for front page","");
regGS("Changing issue template for single article","");
regGS("The template has been successfully changed.","");
regGS("Issue template for publication $1 changed to $2","");
regGS("Issue template for single articles from $1 changed to $2","");
regGS("The template could not be changed.","");


?>